### ISSUE TITLE
Close with Escape button

### ISSUE THREAD

**Issue by besserwisser** [mikavilpas/yazi.nvim#767]
I love the plugin! But most of my floating windows are closed with Escape and Yazi is the only one that is closed with `q`. This can be quite confusing. Is it possible to add an option for closing with "Escape" key as well? Thank you :)

**Comment by mikavilpas** [comment]
Hi! One option is to add this mapping into yazi itself.

In my dotfiles I have mapped it to the up arrow key, for example. In neovim I have also mapped the up arrow key to _open_ yazi, so that I can use the same key to quickly toggle it on and off.

**Comment by besserwisser** [comment]
Thank you!

In the end I put this in `.config/yazi/keymap.toml`:

```toml
[[manager.prepend_keymap]]
on   = "<Esc>"
run  = "close"
desc = "Close"
```
